//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotUygulamasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DERS
    {
        public short OGRID { get; set; }
        public string OGRNUMARA { get; set; }
        public string OGRAD { get; set; }
        public string OGRSOYAD { get; set; }
        public Nullable<byte> OGRSINAV1 { get; set; }
        public Nullable<byte> OGRSINAV2 { get; set; }
        public Nullable<byte> OGRSINAV3 { get; set; }
        public Nullable<decimal> ORT { get; set; }
        public Nullable<bool> DURUM { get; set; }
    }
}
